services:
    nginx:
        image: nginx
        env_file:
          - db.env
        ports:
            - "8443:443"
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/app
            - ../../local-ssl/certs:/var/certs
        #command: ["nginx", "-c", "/var/app/nginx.conf"]
    nextcloud:
        image: nextcloud
        env_file:
          - db.env
        environment:
            - OVERWRITEHOST=192.168.0.253:8443
            - OVERWRITEPROTOCOL=https
            - POSTGRES_HOST=postgres-db
        restart: always
        volumes:
            - nc_data:/var/www/html
    postgres-db:
        image: postgres:alpine
        env_file:
          - db.env
        restart: always
        volumes:
          - db_data:/var/lib/postgresql/data
volumes:
    db_data:
    nc_data: